### PR TITLE
Cleans up some gamemode code

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
# About the pull request
Renames the gamemodes as per the Host's preference.
Renames a file to be more clear.
Adds in one comment to be more clear on where it is overwritten.

# Changelog

:cl:
code: Backend fix on gamemode code.
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Still needs some work. Some names are out of order

**Comment by Kitsunemitsu** [comment]
Honestly this code is a fuckign mystery how it doesn't work and how it does not.

**Comment by Kitsunemitsu** [comment]
Fixed it, this works for real this time.

**Review by Ireuldiz — APPROVED** [review]
ALL IS WELL

**Pull request merged**
